### ISSUE TITLE
Gemeinsames Treffen?

### ISSUE THREAD

**Issue by progwolff** [optNGUI/Projekt-KI#2]
Treffen wir uns nochmal gemeinsam, um zu klären, wie die grobe Schnittstelle zwischen GUI und Kern aussieht, bzw. was die GUI alles können muss?
Oder sagen wir euch einfach, was wir können und ihr bindet das dann an?

**Comment by StdCG** [comment]
Wenn es nach mir geht, reicht es wenn ihr mir Bescheid gebt, was ihr euch bisher so gedacht habt.
Dann kann ich euch auch bei der Gelegenheit erzählen, was die Planung für die GUI  bisher ergeben hat. Ich kann nächsten Mittwoch einfach mit zu euch kommen, dann machen wir das und ich geb die 
Ergebnisse an Szymon weiter. Ausser natürlich, er will dabei sein. Ich glaube aber nicht, dass das 
bei seinem engen Terminplan nötig ist.

**Comment by polemon** [comment]
Letzten Dienstag sprachen wir über die genauere implementierung der Auswahl der Algorithmen.
Entweder wir hardcoden die, oder wir benutzen eine art Spec-File.

Mir ist es rel. gleich wie's gemacht werden sollte, aber /falls/ es mit Spec-Files gehandhabt werden sollte, wäre schonmal ein Format interessant. Ich schlage JSON vor.

Auch: was haltet ihr von einem IRC-Channel bezüglich dieses Projektes?

**Comment by loqust** [comment]
Derzeit ist der Stand der Dinge, dass der Kern eine Liste der verfügbaren Algorithmen bereithält (er erstellt diese Liste zur Laufzeit, indem er die verfügbaren Methoden in core/algorithms.py aufzählt). Diese Liste kann dann über einen einfachen Befehl über die Message-Queue angefordert werden.
