### ISSUE TITLE
Gtk Ttk auf die Pool Rechner pls

### ISSUE THREAD

**Issue by StdCG** [optNGUI/Projekt-KI#3]
Hallo @ChristophMetzner ,

das hätte ich vll dazu sagen sollen ;) 
Also Gtk und Ttk wäre noch äusserst praktisch auf den Pool-Rechnern.

VG Chris

**Comment by ChristophMetzner** [comment]
Ok wird erledigt.

Christoph

**Comment by StdCG** [comment]
Dankesehr
