### ISSUE TITLE
Tabs/Spaces

### ISSUE THREAD

**Issue by loqust** [optNGUI/Projekt-KI#4]
@polemon @StdCG 
Ich krieg hier beim Ausführen per --gui grad einen TabError aus euren Dateien. Nur bei mir oder auch bei euch?

**Comment by StdCG** [comment]
Wir haben 4 leerzeichen als Tab-konfiguration eingestellt. Ich hab hier noch keine Möglichkeit gefunden das als Auflage festzulegen. Du meintest mal das geht über github?

**Comment by loqust** [comment]
4 Leerzeichen haben wir auch. Ich weiß nicht, ob das über Github geht. Ich habe bei mir im Editor eingestellt, dass Tabs als vier Leerzeichen eingefügt werden (wie ihr wohl auch). Nur habe ich in euren Dateien ab und zu gesehen, dass dort noch \t anstatt vier Leerzeichen drin waren.

**Comment by loqust** [comment]
Müsste man nur ein Programm drüberlaufen lassen, welces die umwandelt. Kann ich nachher machen, wenn ihr wollt.
